INSERT INTO USERS (USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES ('ADMIN', '$2A$08$LDNHPZ7EUKSI6AO14TWUAU08MZHWRL4KYZGGU5XFIGALO/VXD5DOI', 'ADMIN', 1);
INSERT INTO USERS (USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES ('USER', '$2A$08$UKVVWPULIS18S19S5PZFN.YHPZT3OAQHZNDWQBCW9PFT6UFTKXKDC', 'USER', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (2, 'ROLE_USER');