CREATE TABLE USER
(
    USER_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME  VARCHAR(50) UNIQUE,
    PASSWORD  VARCHAR(100),
    NICKNAME  VARCHAR(50),
    ACTIVATED BOOLEAN
);


CREATE TABLE USER_AUTHORITY
(
    USER_ID        BIGINT,
    AUTHORITY_NAME VARCHAR(255),
    PRIMARY KEY (USER_ID, AUTHORITY_NAME),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (AUTHORITY_NAME) REFERENCES AUTHORITY (AUTHORITY_NAME)
);

CREATE TABLE AUTHORITY
(
    AUTHORITY_NAME VARCHAR(50) PRIMARY KEY
);
